#!/bin/bash

# Color codes for formatted output
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
RED='\033[0;31m'
NC='\033[0m'

STUDENT_NAME="Ashmit"

echo -e "${PURPLE}============================================================${NC}"
echo -e "${CYAN}         KERNEL DIRECTORY AUDIT REPORT                      ${NC}"
echo -e "${PURPLE}============================================================${NC}"
echo -e "${WHITE}Generated by: $STUDENT_NAME${NC}"
echo ""

# Directories to audit
DIRS=(
    "/boot"
    "/proc"
    "/sys"
    "/lib/modules"
    "/usr/src"
    "/etc/modprobe.d"
    "/etc/modules-load.d"
)

echo -e "${YELLOW}--- DIRECTORY AUDIT ---${NC}"
echo ""

for DIR in "${DIRS[@]}"; do
    if [ -d "$DIR" ]; then
        
        # Get permissions, owner and group
        PERMS=$(ls -ld "$DIR" 2>/dev/null | awk '{print $1, $3, $4}')
        
        # /proc and /sys are virtual filesystems
        if [ "$DIR" = "/proc" ] || [ "$DIR" = "/sys" ]; then
            SIZE="Virtual Filesystem"
        else
            SIZE=$(sudo du -sh "$DIR" 2>/dev/null | cut -f1)
            [ -z "$SIZE" ] && SIZE="N/A"
        fi
        
        printf "${WHITE}%-20s${NC} => %-35s => %s\n" "$DIR" "$PERMS" "$SIZE"
    else
        echo -e "${RED}⚠ $DIR does not exist${NC}"
    fi
done

echo ""
echo -e "${YELLOW}--- BOOT DIRECTORY DETAILS ---${NC}"

if [ -d "/boot" ]; then
    echo -e "${WHITE}Kernel images:${NC}"
    ls -lh /boot/vmlinuz* 2>/dev/null | awk '{printf "  %-40s %s\n", $9, $5}'
    
    echo ""
    echo -e "${WHITE}Initramfs images:${NC}"
    ls -lh /boot/initrd* 2>/dev/null | awk '{printf "  %-40s %s\n", $9, $5}'
fi

echo ""
echo -e "${YELLOW}--- MODULE STATISTICS ---${NC}"

if [ -d "/lib/modules" ]; then
    for version in $(ls /lib/modules/); do
        MODULE_COUNT=$(find /lib/modules/$version -name "*.ko" 2>/dev/null | wc -l)
        echo -e "${WHITE}  $version: $MODULE_COUNT modules${NC}"
    done
fi

echo ""
echo -e "${YELLOW}--- EXTRA CHECK: CURRENT LOADED MODULES ---${NC}"

LOADED=$(lsmod | wc -l)
echo -e "${WHITE}Currently loaded modules: $((LOADED - 1))${NC}"

echo ""
echo -e "${PURPLE}============================================================${NC}"