#!/bin/bash

# Color codes for formatted output
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
RED='\033[0;31m'
NC='\033[0m'

STUDENT_NAME="Ashmit"

echo -e "${PURPLE}============================================================${NC}"
echo -e "${CYAN}         KERNEL LOG ANALYZER                                 ${NC}"
echo -e "${PURPLE}============================================================${NC}"
echo -e "${WHITE}Generated by: $STUDENT_NAME${NC}"
echo ""

# Select log source (kern.log or fallback to dmesg)
if [ -f "/var/log/kern.log" ] && [ -r "/var/log/kern.log" ]; then
    LOG_SOURCE="/var/log/kern.log"
    echo -e "${WHITE}Using log file: $LOG_SOURCE${NC}"
elif command -v dmesg > /dev/null; then
    LOG_SOURCE="dmesg"
    echo -e "${WHITE}Using dmesg for kernel logs${NC}"
else
    echo -e "${RED}Error: Cannot access kernel logs${NC}"
    exit 1
fi

KEYWORD=${1:-"error"}
COUNT=0

echo -e "Analyzing for keyword: ${YELLOW}$KEYWORD${NC}"
echo ""

# If using dmesg, save output to a temporary file
if [ "$LOG_SOURCE" = "dmesg" ]; then
    dmesg > /tmp/kernel_logs.txt
    LOG_FILE="/tmp/kernel_logs.txt"
else
    LOG_FILE="$LOG_SOURCE"
fi

declare -a LAST_MATCHES

# Read file line by line and count keyword matches
while IFS= read -r line; do
    if echo "$line" | grep -iq "$KEYWORD"; then
        COUNT=$((COUNT + 1))
        LAST_MATCHES+=("$line")
        if [ ${#LAST_MATCHES[@]} -gt 10 ]; then
            unset 'LAST_MATCHES[0]'
            LAST_MATCHES=("${LAST_MATCHES[@]}")
        fi
    fi
done < "$LOG_FILE"

echo -e "${PURPLE}============================================================${NC}"
echo -e "${CYAN}SUMMARY${NC}"
echo -e "${PURPLE}============================================================${NC}"
echo -e "Keyword '${YELLOW}$KEYWORD${NC}' found: ${RED}$COUNT${NC} times"
echo ""

if [ $COUNT -eq 0 ]; then
    echo -e "${WHITE}✓ No $KEYWORD entries found. Kernel appears healthy!${NC}"
elif [ $COUNT -lt 10 ]; then
    echo -e "${YELLOW}⚠ $COUNT $KEYWORD entries found. Review below.${NC}"
else
    echo -e "${RED}✗ High number of $KEYWORD entries! Investigate immediately.${NC}"
fi

echo ""
echo -e "${YELLOW}--- LAST 10 MATCHING ENTRIES ---${NC}"
for line in "${LAST_MATCHES[@]}"; do
    echo "$line" | cut -c1-200
done

echo ""
echo -e "${YELLOW}--- QUICK STATS ---${NC}"
TOTAL_LINES=$(wc -l < "$LOG_FILE")
echo -e "${WHITE}Total log lines scanned: $TOTAL_LINES${NC}"

echo ""
echo -e "${YELLOW}--- RECOMMENDATIONS ---${NC}"
echo "1. Check hardware: sudo dmesg | grep -i hardware"
echo "2. Check memory: free -h"
echo "3. Check disk: df -h"
echo "4. Check services: systemctl list-units --failed"

# Remove temporary file if created
[ -f "/tmp/kernel_logs.txt" ] && rm /tmp/kernel_logs.txt

echo ""
echo -e "${YELLOW}--- PROJECT CONTEXT ---${NC}"
echo -e "This script demonstrates log analysis using loops, conditions, and arrays."
echo -e "It is part of the Open Source Software audit project."

echo ""
echo -e "${PURPLE}============================================================${NC}"